name: Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  BUILD_TYPE: Debug

jobs:
  test:
    name: Windows Tests
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up MSVC developer command prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install vcpkg dependencies
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ github.workspace }}/vcpkg

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        run: >
          cmake -B "${{ steps.strings.outputs.build-output-dir }}"
          -A x64
          -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake"
          -DBUILD_TESTING=ON
          -DDTA_BUILD_PYTHON_BINDINGS=ON
          -S "${{ github.workspace }}"

      - name: Build
        run: cmake --build "${{ steps.strings.outputs.build-output-dir }}" --config ${{ env.BUILD_TYPE }}

      - name: Test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: ctest --build-config ${{ env.BUILD_TYPE }} --output-on-failure
